# This file generates the GitHub Actions matrix.

board:
  - nice_nano_v2

shield:
  - scylla_left
  - scylla_right
  - settings_reset

format:
  - bt
  - reset

keymap:
  - qwerty

include:
  - board: nice_nano_v2
    shield: scylla_right
    keymap: qwerty
    snippet: studio-rpc-usb-uart
